### ISSUE TITLE
isClass return false when using multiple 30log instances

### ISSUE THREAD

**Issue by pehbehbeh** [Yonaba/30log#23]
Because of the way `isClass` works, it returns false if you are using multiple 30log instances when you check for a class from another instance.

For example when you have a subproject with it's own 30log library. Then you can not check for classes from that subroject in your main project wich is also using it's own 30log from another subfolder/file.

This is not much of an issue, if you are in control of the subproject because you can check for a global 30log or something with a simple workaround.

But maybe you have an idea to solve that kind of problem? Maybe with an (optional) global classes-table or something?

**Comment by Yonaba** [comment]
This is definitely true, since each instance of *30log* keeps internally tracks of all new classes created. Creating a global register might be a workaround, but this is not an ideal solution to me, since I would like to keep the global environment safe. 

I can also rewrite the `isClass` method, but that would require multiple checks and can be easily fooled in case one would pass a properly formatted table.

As I cannot see any elegant solution, I am closing this. Let us consider in case one requires multiple instances of *30log*, it is advised to use the proper instance to perform the `isClass` check.
