### ISSUE TITLE
the table is not copy~~

### ISSUE THREAD

**Issue by wilhantian** [Yonaba/30log#27]
my code:
var Obj = class("Obj", {
tab = {}
})

var o1 = Obj:new()
var o2 = Obj:new()
o2.tab.x = "BiuBiuBiu"

print(o1.tab.x) --BiuBiuBiu
print(o2.tab.x) --BiuBiuBiu

it`s a bug? or I understand the wrong？

**Comment by zorfmorf** [comment]
The problem is that you are assigning a new table to Obj.tab during class creation. This means that all your tables that inherit from Obj will share the same tab table. You need to put code like that into the init method.

```lua
> class = require '30log'
> Obj = class("Obj")
> function Obj:init() self.tab = {} end
> o1 = Obj:new()
> o2 = Obj:new()
> o1.tab.x = "BuiBuiBui"
> print(o1.tab.x)
BuiBuiBui
> print(o2.tab.x)
nil
> 
```

And what's up with the "var" definition? Did you replace the "local" keyword?

**Comment by wilhantian** [comment]
OH, very sorry, I write too much js, it`s local.  very thanks for you!

**Comment by Yonaba** [comment]
Although @zorfmorf provided a nice solution, the latest commit should provide some fix to the code.
Try this new one, it should be working nicely.

```lua
local Obj = class("Obj", {
tab = {}
})

local o1 = Obj:new()
local o2 = Obj:new()
o2.tab.x = "BiuBiuBiu"

print(o1.tab.x) -- outputs nil
print(o2.tab.x) -- outputs BiuBiuBiu
````

**Comment by wilhantian** [comment]
@Yonaba yes, It`s no problem. Now it`s OK. 
非常谢谢。

**Comment by Yonaba** [comment]
Awesome! Thanks reporting this.
